version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/ruby/Dockerfile
    volumes:
      - .:/app
      - bundle-data:/usr/local/bundle
    ports:
      - "8888:8888"
    depends_on:
      - db
    command: bundle exec jets server --port 8888 --host 0.0.0.0
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file:
      - .env.development
volumes:
  bundle-data:
    driver: local
